default: &default
  adapter: postgresql
  username: 'postgres'
  password: 'postgres'
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: silspi_development

test:
  <<: *default
  database: silspi_test

production:
  <<: *default
  database: silspi_production
